# Continuous Delivery - releases automatically on every push to main
name: cd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    uses: jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@v1
    with:
      validate_only: false
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
